### ISSUE TITLE
ntest broken against latest syn crate

### ISSUE THREAD

**Issue by zeenix** [becheran/ntest#10]
zbus [CI is failing](https://gitlab.freedesktop.org/zeenix/zbus/-/jobs/6489730) because ntest seems to be using `syn::export` that is not present/pub in the latest `syn` release. Seems this [API was always internal-only](https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7) and shouldn't have been used.

**Comment by becheran** [comment]
Thanks for reporting. I will look into it and find a solution as soon as I have the time.

**Comment by becheran** [comment]
Removed the wrong dependency with release 0.7.3

**Comment by zeenix** [comment]
> Removed the wrong dependency with release 0.7.3

Thanks, yes I saw. Rerunning my build now hoping it picks up 0.7.3 this time. Thanks for the very quick action!
