### ISSUE TITLE
`timeout` attribute reports timeout even when test panics

### ISSUE THREAD

**Issue by YuhanLiin** [becheran/ntest#13]
**Describe the bug**
When the `timeout` attribute is put on a test and that test panics, the test reports that the test timed out, even though it didn't.

**To Reproduce**
Run this code:
```rust
#[cfg(test)]
mod tests {
    use ntest::timeout;

    #[test]
    #[timeout(20000)]
    fn panic() {
        assert!(false);
    }
}
```

Results in this output:
```
thread '<unnamed>' panicked at 'assertion failed: false', src/lib.rs:8:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tests::panic' panicked at 'timeout: the function call took 0 ms. Max time 20000 ms', src/lib.rs:6:5
```

The output should instead be this:
```
thread 'tests::panic' panicked at 'assertion failed: false', src/lib.rs:7:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Additional context**
The fix is likely in `ntest_proc_macro_helper`, which needs to be changed to handle test panics.

**Comment by becheran** [comment]
@YuhanLiin thanks for reporting! I will look into it once I find time (right now hard to find :( )

**Comment by becheran** [comment]
Not 100% fixed, but better. Do not panic with misleading timeout error message, and use a empty panic insteead if test func panics. Second panic is still needed because panic happens in another thread. See c1dd5c60c8bc0b37ac54fbf5788a7d6b38bd1180

**Comment by YuhanLiin** [comment]
Would be better if the second panic message indicates an inner panic, but as long as the inner panic message is visible then it's fine.
