### ISSUE TITLE
Version 0.8.1 not in repo?

### ISSUE THREAD

**Issue by roblabla** [becheran/ntest#17]
Heya, I see that `ntest` had a 0.8.1 release on crates.io (https://crates.io/crates/ntest) but that release is not tagged on github, and it looks like the master branch is still on 0.8.0 (at least, the ntest crate's Cargo.toml claims to be version 0.8.0). According to [the source uploaded to crates.io](https://docs.rs/crate/ntest/0.8.1/source/.cargo_vcs_info.json), version 0.8.1 was made from git commit a858d8a9683504cb98fd2408e44987c53ae367dd, but that commit [does not exist on github](https://github.com/becheran/ntest/commit/a858d8a9683504cb98fd2408e44987c53ae367dd).

Could you publish the latest changes?

Thanks for the great crate :)

**Comment by becheran** [comment]
Ups. Thx. Seems like I forgot to push last time. Did it now
