### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Lorak-mmk** [becheran/ntest#26]
Hi, are there any plans to release new version of ntest?
Last release was in 2022, since then there was a PR that afaik prevented rust-analyzer not working with ntest + tokio::test: https://github.com/becheran/ntest/pull/23
It was merged in July but is still not part of any release :(

**Comment by becheran** [comment]
Sorry for that! Thanks for raising this. Definitely not good. I will create a new release ASAP.

**Comment by Lorak-mmk** [comment]
Thank you very much, it doesn't crash rust-analyzer now <3
