### ISSUE TITLE
feature request: timeout that passes instead of fails

### ISSUE THREAD

**Issue by amab8901** [becheran/ntest#29]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a test that runs for X amount of time. if no errors occur within this time, then the test is successful.

**Describe the solution you'd like**
[timeout attribute](https://docs.rs/ntest/0.9.3/ntest/attr.timeout.html) but labeling the test successful rather than failed, when the timeout is reached.

**Describe alternatives you've considered**
Haven't found any alternatives that work

**Comment by becheran** [comment]
@amab8901 thanks for opening the issue. Can you provide a minimum failing example that does not work as expected with the timeout attribute?

**Comment by amab8901** [comment]
```
#[test]
#[timeout_pass(10)]
fn pass_if_timeout() {}

```

**Comment by becheran** [comment]
Ah OK. Can I ask what the usecase of such a test would be? Having a test which passes when for a certain time nothing panics?

**Comment by amab8901** [comment]
integration testing. I run the program X number of seconds. if nothing paniced, then the program is fine.

**Comment by becheran** [comment]
I see. Wouldn't something like this also be enough in your case?

```rust
#[test]
fn timeout_forever() {
    // Run never ending function in parallel
    // fail test if panic in other thread
    let handle = thread::spawn(|| panic!("foo"));
    thread::sleep(time::Duration::from_secs(5));
    if handle.is_finished() {
        let result = handle.join();
        assert!(result.is_err(), "Spawned thread should have panicked");
    }
}
```

**Comment by amab8901** [comment]
I found that I can test my case by having an environment variable that runs the program's main loop only once before exiting, and I set that env inside the integration test so that the test exits after running just 1 loop
